name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest' ]
        java: [ '17', '18', '19', '20', '21' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup build
        uses: MOEAFramework/.github/actions/setup-build@main
        with:
          java-version: ${{ matrix.java }}
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install unrar
      - name: Run tests
        run: mvn test
